# How to use the R package `arules` from Python using `arulespy`

This document is also available as an [IPython notebook](https://github.com/mhahsler/arulespy/blob/main/examples/arules.ipynb) or you can open and run it directly in 
[Google Colab](https://colab.research.google.com/github/mhahsler/arulespy/blob/main/examples/arules.ipynb).

## Installation 

This notebook needs `arulespy` installed (see [arulespy GitHub page](https://github.com/mhahsler/arulespy)). 
On Google Colab, uncomment the installation instruction in following code block.

In [ ]:
# %pip install arulespy

## Basic Usage

Import the `arules` module from package `arulespy`. This will take a while if you run it for the first time since it needs to install all the needed R packages.

In [4]:
from arulespy.arules import Transactions, apriori, parameters, concat

### Creating transaction data

The data need to be prepared as a Pandas dataframe. Here we have 9 transactions with three items called A, B and C. True means that a transaction contains the item.

In [5]:
import pandas as pd

df = pd.DataFrame (
    [
        [True,True, True],
        [True, False,False],
        [True, True, True],
        [True, False, False],
        [True, True, True],
        [True, False, True],
        [True, True, True],
        [False, False, True],
        [False, True, True],
        [True, False, True],
    ],
    columns=list ('ABC')) 

df

       A      B      C
0   True   True   True
1   True  False  False
2   True   True   True
3   True  False  False
4   True   True   True
5   True  False   True
6   True   True   True
7  False  False   True
8  False   True   True
9   True  False   True

Convert the pandas dataframe into a sparse transactions object.

In [6]:
trans = Transactions.from_df(df)
print(trans)

trans.as_df()

transactions in sparse format with
 10 transactions (rows) and
 3 items (columns)

      items transactionID
1   {A,B,C}             0
2       {A}             1
3   {A,B,C}             2
4       {A}             3
5   {A,B,C}             4
6     {A,C}             5
7   {A,B,C}             6
8       {C}             7
9     {B,C}             8
10    {A,C}             9

In [7]:
trans.item_labels()

['A', 'B', 'C']

### Working with transactions

We can calculate item frequencies, sample transactions or remove duplicate transactions. All available functions can be found at the end of this document.

In [8]:
trans.item_frequency(type = 'relative')

[0.8, 0.5, 0.8]

In [9]:
trans.sample(3).as_df()

     items transactionID
6    {A,C}             5
5  {A,B,C}             4
2      {A}             1

In [10]:
trans.unique().as_df()

     items transactionID
1  {A,B,C}             0
2      {A}             1
6    {A,C}             5
8      {C}             7
9    {B,C}             8

Create new data that uses the same encoding as an existing transaction set from a pandas dataframe. Note that the following dataframe
has the columns (items) in reverse order which is fixed when the itemencoding in `trans` is used.

In [11]:
trans2 = Transactions.from_df(pd.DataFrame (
    [
        [True,True, False],
        [False, False, True],
    ],
    columns=list ('CBA')), trans)

trans2.as_df()

   items transactionID
1  {B,C}             0
2    {A}             1

Create the same transaction, but from a list of lists. Note that the order of the items is fixed to match `trans`.

In [12]:
trans3 = Transactions.from_list([['B', 'A'],
                        ['C']], 
                        trans)

trans3.as_df()

   items
1  {A,B}
2    {C}

Add the new transaction to the existing transactions.

In [13]:
concat([trans, trans2]).as_df()

      items transactionID
1   {A,B,C}             0
2       {A}             1
3   {A,B,C}             2
4       {A}             3
5   {A,B,C}             4
6     {A,C}             5
7   {A,B,C}             6
8       {C}             7
9     {B,C}             8
10    {A,C}             9
11    {B,C}             0
12      {A}             1

### Converting transactions into Python data strucutres

Transactions can be converted into several Python formats inclusing 0-1 matrices, lists of item labels, lists of item idices or a sparse matrix.

In [14]:
trans.as_matrix()

array([[1, 1, 1],
       [1, 0, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 1, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 1, 1],
       [1, 0, 1]], dtype=int32)

In [15]:
trans.as_list()

[['A', 'B', 'C'],
 ['A'],
 ['A', 'B', 'C'],
 ['A'],
 ['A', 'B', 'C'],
 ['A', 'C'],
 ['A', 'B', 'C'],
 ['C'],
 ['B', 'C'],
 ['A', 'C']]

In [16]:
trans.as_int_list()

[[1, 2, 3],
 [1],
 [1, 2, 3],
 [1],
 [1, 2, 3],
 [1, 3],
 [1, 2, 3],
 [3],
 [2, 3],
 [1, 3]]

In [17]:
trans.as_csc_matrix()

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 21 stored elements and shape (3, 10)>

### Mixing nominal and numeric variables

Converting a dataframe with nominal and numeric variables. The nominal variables are converted into the form `variable=value` and
numeric variables are first discretized (see `arules.discretize_df()`).

In [18]:
df2 = pd.DataFrame (
    [
        ['red',  12, True],
        ['blue', 10, False],
        ['red',  18, True],
        ['green',18, False],
        ['red',  16, True],
        ['blue',  9, False]
    ],
    columns=list(['color', 'size', 'class'])) 

trans2 = Transactions.from_df(df2)
trans2.as_df()

                                items transactionID
1  {color=red,size=[11.3,16.7),class}             0
2          {color=blue,size=[9,11.3)}             1
3    {color=red,size=[16.7,18],class}             2
4        {color=green,size=[16.7,18]}             3
5  {color=red,size=[11.3,16.7),class}             4
6          {color=blue,size=[9,11.3)}             5

Details on item label creation can be retrieved using `arules.item_info()`.

In [19]:
trans2.item_info()

             labels variables       levels
1        color=blue     color         blue
2       color=green     color        green
3         color=red     color          red
4     size=[9,11.3)      size     [9,11.3)
5  size=[11.3,16.7)      size  [11.3,16.7)
6    size=[16.7,18]      size    [16.7,18]
7             class     class         TRUE

## Mine association rules

`arules.apriori()` calls the apriori algorithm and converts the results into a Python `arulespy.arules.Rules` object. Parameters for the algorithm
are specified as `dict` inside the `arules.parameter()` funcition.

In [20]:
rules = apriori(trans,
                    parameter = parameters({"supp": 0.1, "conf": 0.8}), 
                    control = parameters({"verbose": False}))  


rules.as_df()

     LHS  RHS  support  confidence  coverage  lift  count
1     {}  {A}      0.8         0.8       1.0  1.00      8
2     {}  {C}      0.8         0.8       1.0  1.00      8
3    {B}  {A}      0.4         0.8       0.5  1.00      4
4    {B}  {C}      0.5         1.0       0.5  1.25      5
5  {A,B}  {C}      0.4         1.0       0.4  1.25      4
6  {B,C}  {A}      0.4         0.8       0.5  1.00      4

In [21]:
rules.quality()

   support  confidence  coverage  lift  count
1      0.8         0.8       1.0  1.00      8
2      0.8         0.8       1.0  1.00      8
3      0.4         0.8       0.5  1.00      4
4      0.5         1.0       0.5  1.25      5
5      0.4         1.0       0.4  1.25      4
6      0.4         0.8       0.5  1.00      4

Python-style `len()` and slicing is available.

In [22]:
len(rules)

6

In [23]:
rules[0:3].as_df()

   LHS  RHS  support  confidence  coverage  lift  count
1   {}  {A}      0.8         0.8       1.0   1.0      8
2   {}  {C}      0.8         0.8       1.0   1.0      8
3  {B}  {A}      0.4         0.8       0.5   1.0      4

In [24]:
rules[[True, False, True, False, True, False]].as_df()

     LHS  RHS  support  confidence  coverage  lift  count
1     {}  {A}      0.8         0.8       1.0  1.00      8
3    {B}  {A}      0.4         0.8       0.5  1.00      4
5  {A,B}  {C}      0.4         1.0       0.4  1.25      4

### Accessing Rules

rules can be converted into various Python data structures.

In [25]:
rules.labels()

['{} => {A}',
 '{} => {C}',
 '{B} => {A}',
 '{B} => {C}',
 '{A,B} => {C}',
 '{B,C} => {A}']

In [26]:
rules.items().as_df()

     items
1      {A}
2      {C}
3    {A,B}
4    {B,C}
5  {A,B,C}
6  {A,B,C}

In [27]:
rules.lhs().as_df()

   items
1     {}
2     {}
3    {B}
4    {B}
5  {A,B}
6  {B,C}

In [28]:
rules.lhs().as_list()

[[], [], ['B'], ['B'], ['A', 'B'], ['B', 'C']]

In [29]:
rules.rhs().as_df()

  items
1   {A}
2   {C}
3   {A}
4   {C}
5   {C}
6   {A}

The LHS and RHS of rules are of type `itemMatrix` in the same way are `transactions` are. Therefore, all conversions (to lists, sparce matrices, etc.) are also availabe.

In [30]:
rules.sort(by = 'lift').as_df()

     LHS  RHS  support  confidence  coverage  lift  count
4    {B}  {C}      0.5         1.0       0.5  1.25      5
5  {A,B}  {C}      0.4         1.0       0.4  1.25      4
1     {}  {A}      0.8         0.8       1.0  1.00      8
2     {}  {C}      0.8         0.8       1.0  1.00      8
3    {B}  {A}      0.4         0.8       0.5  1.00      4
6  {B,C}  {A}      0.4         0.8       0.5  1.00      4

### Work With Interest Measures

Interest measures are stored as the quality attribute in rules and itemsets.

In [31]:
rules.quality()

   support  confidence  coverage  lift  count
1      0.8         0.8       1.0  1.00      8
2      0.8         0.8       1.0  1.00      8
3      0.4         0.8       0.5  1.00      4
4      0.5         1.0       0.5  1.25      5
5      0.4         1.0       0.4  1.25      4
6      0.4         0.8       0.5  1.00      4

Additional interest measures can be calculated with `interest_measure()` and added to rules or itemsets using `add_quality()`. See all [available meassures](https://mhahsler.github.io/arules/docs/measures). To calculate some measures, transactions need to
be specified.

In [32]:
im = rules.interest_measure(["phi", 'support'])
im

        phi  support
1       NaN      0.8
2       NaN      0.8
3  0.000000      0.4
4  0.500000      0.5
5  0.408248      0.4
6  0.000000      0.4

In [33]:
rules.add_quality(im)
rules.as_df()

     LHS  RHS  support  confidence  coverage  lift  count       phi
0     {}  {A}      0.8         0.8       1.0  1.00      8       NaN
1     {}  {C}      0.8         0.8       1.0  1.00      8       NaN
2    {B}  {A}      0.4         0.8       0.5  1.00      4  0.000000
3    {B}  {C}      0.5         1.0       0.5  1.25      5  0.500000
4  {A,B}  {C}      0.4         1.0       0.4  1.25      4  0.408248
5  {B,C}  {A}      0.4         0.8       0.5  1.00      4  0.000000

### Filter Redundant Rules

In [34]:
rules[[not x for x in rules.is_redundant()]].as_df()

   LHS  RHS  support  confidence  coverage  lift  count  phi
0   {}  {A}      0.8         0.8       1.0  1.00      8  NaN
1   {}  {C}      0.8         0.8       1.0  1.00      8  NaN
3  {B}  {C}      0.5         1.0       0.5  1.25      5  0.5

In [35]:
rules.is_redundant()

[False, False, True, False, True, True]

Find maximal rules.

In [36]:
rules.is_maximal()

[False, False, False, False, True, True]

## Create Rules Objects

To import rules from other tools or to create rules manually, rules for `arules` can be created from lists 
of sets of items. The item labels (i.e., the sparse representation) is
taken from the transactions `trans`.

The LHS and RHS of rules are of tpye `itemMatrix` and can be created by conversion form pandas data fames of lists of lists.

In [37]:
import rpy2.robjects as ro
from arulespy.arules import Rules, ItemMatrix

trans = Transactions.from_df(pd.read_csv("https://mhahsler.github.io/arulespy/examples/Zoo.csv"))


lhs = [
    ['hair', 'milk', 'predator'],
    ['hair', 'tail', 'predator'],
    ['fins']
]
rhs = [
    ['type=mammal'],
    ['type=mammal'],
    ['type=fish']
]

r = Rules.new(ItemMatrix.from_list(lhs, itemLabels = trans), 
              ItemMatrix.from_list(rhs, itemLabels = trans))

r.as_df()

                    LHS            RHS
1  {hair,milk,predator}  {type=mammal}
2  {hair,predator,tail}  {type=mammal}
3                {fins}    {type=fish}

Next, we add interest measures calculated on the transactions.

In [38]:
r.add_quality(r.interest_measure(['support', 'confidence', 'lift'], trans))

r.as_df().round(2)

                    LHS            RHS  support  confidence  lift
0  {hair,milk,predator}  {type=mammal}     0.20        1.00  2.46
1  {hair,predator,tail}  {type=mammal}     0.16        1.00  2.46
2                {fins}    {type=fish}     0.13        0.76  5.94

## Find Super and Subsets

Subset calcualtion returns a large binary matrix. Since this matrix is often sparse, it is represented as a sparse matrix. For example,
subset can be used to check which transactions contain the items in the LHS of the rules. The result is a number of transactions
by number of rules sparse matrix.

In [39]:
superset = trans.is_superset(r.lhs(), sparse = True)
superset

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 53 stored elements and shape (101, 3)>

In [40]:
superset[0:1, ].toarray()

array([[1, 0, 0]])

Show first row as a dense vector. Transaction 1 is a superset of the LHS of the first rule. That is, transaction 1 contains the items in the LHS of Rule 1.

In [41]:
print("Transaction 1:", trans[0:1].as_list(), "\n")

print("Rule 1:\n", r[0:1].as_df())

Transaction 1: [['hair', 'milk', 'predator', 'toothed', 'backbone', 'breathes', 'legs=[4,8]', 'catsize', 'type=mammal']]

Rule 1:
                     LHS            RHS  support  confidence      lift
0  {hair,milk,predator}  {type=mammal}  0.19802         1.0  2.463415

This information can be used to find the LHS support count for the three rules by summing along the columns.

In [42]:
superset.sum(axis = 0)

## Online Help for Functions Available via arulespy

In [ ]:
help(apriori)

## Low-level R arules interface

arules functions can also be directly called using
`R_arules.<arules R function>()` and `R_arulesViz.<arules R function>()`. The result will be a `rpy2` data type.
Transactions, itemsets and rules can manually be converted to Python
classes using.

In [ ]:
from arulespy.arules import R_arules, Itemsets, arules_to_py

In [ ]:
help(R_arules.random_patterns)

In [ ]:
its_r = R_arules.random_patterns(100, 10)
its_r

Since we directly called a R function, we need to manually wrap the R object as a Python object before we use it in Python.

In [ ]:
its_p = Itemsets(its_r)
its_p.as_df()

In [ ]:
trans = arules_to_py(R_arules.random_transactions(10, 1000))

print(trans)

Access directly the sparse representation.

In [ ]:
from scipy.sparse import csc_matrix

trans.items().as_csc_matrix()